language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=2.8.*

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*@dev

install:
  - composer update --prefer-source $COMPOSER_FLAGS
  - php Tests/bin/console doctrine:database:create --env=test
  - php Tests/bin/console doctrine:schema:create --env=test

script: phpunit --coverage-text
