services:
    alpixel_menu.builder:
       class: Alpixel\Bundle\MenuBundle\Builder\MenuBuilder
       arguments: ["@doctrine.orm.entity_manager", "@knp_menu.factory"]

    alpixel_menu.twig.menu.extension:
        class: Alpixel\Bundle\MenuBundle\Twig\MenuExtension
        public: true
        arguments: ["@alpixel_menu.builder"]
        tags:
            - { name: twig.extension }